const express = require('express');
const PDFDocument = require('pdfkit');
const db = require('../db');
const { verifyToken } = require('../middleware/auth');
const { emit } = require('../utils/notify');

const router = express.Router();
router.use(verifyToken);

router.get('/', async (req, res) => {
  const { rows } = await db.query(`
    SELECT r.*, i.disaster_name, i.disaster_type, i.brgy,
           u.first_name AS author_first, u.last_name AS author_last
    FROM DROMIC_REPORTS r
    LEFT JOIN DISASTER_INCIDENTS i ON i.incident_id = r.incident_id
    LEFT JOIN USERS u ON u.user_id = r.generated_by
    ORDER BY r.report_date DESC
  `);
  res.json(rows);
});

// POST /api/dromic — compiles current stats for an incident into a report
router.post('/', async (req, res) => {
  const { incident_id, field_remarks } = req.body;
  if (!incident_id) return res.status(400).json({ error: 'incident_id is required' });

  const { rows: [report] } = await db.query(
    `INSERT INTO DROMIC_REPORTS (incident_id, generated_by, reporting_status, field_remarks)
     VALUES ($1,$2,'Active',$3) RETURNING *`,
    [incident_id, req.user.user_id, field_remarks || null]
  );
  emit('dromic_report_generated', report);
  res.status(201).json(report);
});

async function compileSummary(reportId) {
  const { rows: [report] } = await db.query(`
    SELECT r.*, i.disaster_name, i.disaster_type, i.brgy, i.severity, i.date_started,
           u.first_name AS author_first, u.last_name AS author_last
    FROM DROMIC_REPORTS r
    LEFT JOIN DISASTER_INCIDENTS i ON i.incident_id = r.incident_id
    LEFT JOIN USERS u ON u.user_id = r.generated_by
    WHERE r.report_id = $1
  `, [reportId]);
  if (!report) return null;

  const centers = await db.query('SELECT * FROM EVACUATION_CENTERS ORDER BY center_name');
  const totals = await db.query(`
    SELECT
      (SELECT COUNT(*)::int FROM EVACUATION_RECORDS WHERE incident_id = $1) AS total_evacuated,
      (SELECT COUNT(*)::int FROM EVACUATION_RECORDS WHERE incident_id = $1 AND status = 'Present') AS currently_present,
      (SELECT COUNT(DISTINCT e.evacuee_id)::int FROM EVACUATION_RECORDS er JOIN EVACUEES e ON e.evacuee_id = er.evacuee_id
         JOIN PRIORITY_CASES p ON p.evacuee_id = e.evacuee_id WHERE er.incident_id = $1) AS priority_count
  `, [report.incident_id]);
  const priorityBreakdown = await db.query(`
    SELECT p.case_type, COUNT(DISTINCT p.evacuee_id)::int AS n
    FROM PRIORITY_CASES p
    JOIN EVACUATION_RECORDS er ON er.evacuee_id = p.evacuee_id
    WHERE er.incident_id = $1
    GROUP BY p.case_type ORDER BY n DESC
  `, [report.incident_id]);

  return { report, centers: centers.rows, totals: totals.rows[0], priorityBreakdown: priorityBreakdown.rows };
}

// GET /api/dromic/:id/summary — the compiled figures the report references
router.get('/:id/summary', async (req, res) => {
  const data = await compileSummary(req.params.id);
  if (!data) return res.status(404).json({ error: 'Report not found' });
  res.json(data);
});

// GET /api/dromic/:id/pdf — A4 printable/downloadable PDF of the report
router.get('/:id/pdf', async (req, res) => {
  const data = await compileSummary(req.params.id);
  if (!data) return res.status(404).json({ error: 'Report not found' });
  const { report, centers, totals, priorityBreakdown } = data;

  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="DROMIC-Report-${report.report_id}.pdf"`);
  doc.pipe(res);

  doc.fontSize(9).fillColor('#555').text('Republic of the Philippines', { align: 'center' });
  doc.text('Municipal Disaster Risk Reduction and Management Office — San Nicolas, Ilocos Norte', { align: 'center' });
  doc.moveDown(0.6);
  doc.fontSize(16).fillColor('#0B1A47').font('Helvetica-Bold')
    .text('DROMIC REPORT', { align: 'center' });
  doc.fontSize(10).fillColor('#555').font('Helvetica')
    .text('Disaster Response Operations Monitoring and Information Center', { align: 'center' });
  doc.moveDown(1);

  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#ddd').stroke();
  doc.moveDown(0.8);

  const row = (label, value) => {
    doc.font('Helvetica-Bold').fontSize(10).fillColor('#0B1A47').text(label, { continued: true, width: 160 });
    doc.font('Helvetica').fillColor('#222').text(`  ${value ?? '—'}`);
  };

  row('Report ID:', `#${report.report_id}`);
  row('Status:', report.reporting_status);
  row('Generated:', new Date(report.report_date).toLocaleString());
  row('Generated By:', `${report.author_first || ''} ${report.author_last || ''}`.trim() || '—');
  doc.moveDown(0.6);
  row('Disaster:', report.disaster_name);
  row('Type:', report.disaster_type);
  row('Barangay:', report.brgy);
  row('Severity:', report.severity);
  row('Date Started:', report.date_started ? new Date(report.date_started).toLocaleString() : '—');
  doc.moveDown(1);

  doc.font('Helvetica-Bold').fontSize(12).fillColor('#0B1A47').text('Summary Figures');
  doc.moveDown(0.3);
  doc.font('Helvetica').fontSize(10).fillColor('#222');
  doc.text(`Total Evacuated (this incident): ${totals.total_evacuated}`);
  doc.text(`Currently Present: ${totals.currently_present}`);
  doc.text(`Priority / Vulnerable Cases: ${totals.priority_count}`);
  doc.moveDown(1);

  if (priorityBreakdown.length) {
    doc.font('Helvetica-Bold').fontSize(12).fillColor('#0B1A47').text('Priority Case Breakdown');
    doc.moveDown(0.3);
    doc.font('Helvetica').fontSize(10).fillColor('#222');
    priorityBreakdown.forEach(p => doc.text(`• ${p.case_type}: ${p.n}`));
    doc.moveDown(1);
  }

  doc.font('Helvetica-Bold').fontSize(12).fillColor('#0B1A47').text('Evacuation Centers');
  doc.moveDown(0.3);
  const colX = [50, 260, 340, 430];
  doc.font('Helvetica-Bold').fontSize(9).fillColor('#555');
  doc.text('Center', colX[0], doc.y, { continued: true, width: 200 });
  doc.text('Barangay', colX[1], doc.y, { continued: true, width: 70 });
  doc.text('Occupancy', colX[2], doc.y, { continued: true, width: 80 });
  doc.text('Status', colX[3], doc.y, { width: 80 });
  doc.moveTo(50, doc.y + 2).lineTo(545, doc.y + 2).strokeColor('#ddd').stroke();
  doc.moveDown(0.4);
  doc.font('Helvetica').fontSize(9.5).fillColor('#222');
  centers.forEach(c => {
    const y = doc.y;
    doc.text(c.center_name, colX[0], y, { width: 200 });
    doc.text(c.barangay, colX[1], y, { width: 70 });
    doc.text(`${c.occupancy} / ${c.capacity}`, colX[2], y, { width: 80 });
    doc.text(c.status, colX[3], y, { width: 80 });
    doc.moveDown(0.35);
  });

  if (report.field_remarks) {
    doc.moveDown(1);
    doc.font('Helvetica-Bold').fontSize(12).fillColor('#0B1A47').text('Field Remarks');
    doc.moveDown(0.3);
    doc.font('Helvetica').fontSize(10).fillColor('#222').text(report.field_remarks, { width: 495 });
  }

  doc.moveDown(2);
  doc.fontSize(8).fillColor('#999').text(`Generated by RESCOM on ${new Date().toLocaleString()}`, { align: 'center' });

  doc.end();
});

router.patch('/:id/status', async (req, res) => {
  const { reporting_status } = req.body;
  const { rows } = await db.query(
    `UPDATE DROMIC_REPORTS SET reporting_status = $1 WHERE report_id = $2 RETURNING *`,
    [reporting_status, req.params.id]
  );
  if (!rows[0]) return res.status(404).json({ error: 'Report not found' });
  emit('dromic_report_generated', rows[0]);
  res.json(rows[0]);
});

module.exports = router;
